### ISSUE TITLE
Add RSS support!

### ISSUE THREAD

**Issue by aredridel** [polyglotweekly/polyglotweekly.com#5]
Would be great to have feeds for those of us who still use feed readers.

**Comment by bcoe** [comment]
I 100% agree, I think this could be added to the build step here:

https://github.com/polyglotweekly/articleify/blob/master/lib/index.js#L14

There's already a step that walks the directories and generates an HTML index.

**Comment by bcoe** [comment]
see: https://github.com/polyglotweekly/articleify/pull/3
