### ISSUE TITLE
headline for announcing polyglotweekly.com project

### ISSUE THREAD

**Issue by bcoe** [polyglotweekly/polyglotweekly.com#6]
I'd like to throw polyglotweekly.com up on HN today, I've found Saturdays/Sundays can be a good time to promote this sort of open-source project. Any thoughts about potential headlines. Some random ideas:

`polyglotweekly.com, a community curated coding blog`

`polyglotweekly.com, a GitHub-powered platform for discussing programming`

... CC: @mmalecki, @markstory, @jameswomack, @aredridel

**Comment by aredridel** [comment]
Fun. Not touching HN, but I'll submit to lobste.rs ;-)

**Comment by bcoe** [comment]
@aredridel I've merged the introductory article, and opted for the first headline.
