### ISSUE TITLE
Reposting "Rustacean learning Go"

### ISSUE THREAD

**Issue by Manishearth** [polyglotweekly/polyglotweekly.com#8]
I wrote [this blog post](http://inpursuitoflaziness.blogspot.in/2015/02/thoughts-of-rustacean-learning-go.html) a few weeks ago. It showcases what Go looks like to someone coming from  a Rust background.

Would you like to host a copy of that post in Polyglot Weekly?

**Comment by bcoe** [comment]
@Manishearth would love to repost a copy of the article, it's a good read. Submit a pull request and we can start the editing process :+1: To get started you should be able to:
- clone this repo.
- run `npm run generate`.
- start editing the article.
- to test you can run `npm run build; npm start`.

You'll want to be running a `0.10.x` copy of Node.js. If you don't feel like going through the trouble of getting Node up and running, you can also use the sample article as a jumping off point, and create a new article manually:

https://raw.githubusercontent.com/polyglotweekly/polyglotweekly.com/master/introducing-polyglotweekly.com.md

**Comment by Manishearth** [comment]
Cool! I'll try my hand at a draft tomorrow then!
